### ISSUE TITLE
Add obj/ to .gitignore

### ISSUE THREAD

**Issue by xKiraiChan** [abbeybabbey/SimpleAntis#1]
The `obj` folder inside of this project contains information about the system building it.
This information includes:
- Your windows username (`Sylvo`)
- Where the game is installed (`D:\SteamLibary\steamapps\common\VRChat`)
- Where you installed dotNET to (`C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2`)

## If this information isn't public

In the future you can avoid this by using Visual Studio itself to add Git, it will automatically create a `.gitignore` file.

For now you can:
- Create a `.gitignore` file in the repository's root folder
- Use `git filter-branch` to delete the folder from history.

Alternatively,
- Delete the `.git` folder
- Create a `.gitignore` file in the repository's root folder
- Initialize the repository and set the origin
- Make a new commit will all of the previous files
- `git push -f`. The `-f` flag will cause it to completely overwrite history with the new history that doesn't include the file.

Every repository you have other than `UdonChangeReflectLayers` leaks the build information (inside of the `.vs` folder)

You *should* be able to edit my issue and remove any information you want private.

**Comment by abbeybabbey** [comment]
Thanks for the information! I hope I did it correctly. I don't really care about that information being public, but your information was still useful.
