### ISSUE TITLE
Was the Anti for collider removal tested?

### ISSUE THREAD

**Issue by abbe** [abbeybabbey/SimpleAntis#2]
Anti for collider removal doesn't work at all in it's current state, the current collider removal uses FLT_MAX, not PositiveInfinity (because it was patched in the latest update I believe). This doesn't seem to be caught at all with this Anti implementation according to a simple test I ran. I'd recommend having some more checks instead of checking NaN only 👍

**Comment by abbeybabbey** [comment]
If you think it's wrong you can contribute. I don't have that much time and I don't talk or hang out around people like that so I haven't tested it fully at all. It happened to me only once.

**Comment by abbeybabbey** [comment]
https://user-images.githubusercontent.com/61197745/119020326-68411880-b99e-11eb-9e2d-7ef0ad53a59a.mp4

seems to work fine, got it twice today both attempts were unsuccessful

**Comment by abbeybabbey** [comment]
should always work now based on your feedback
